### ISSUE TITLE
Some steps are missing in the setup instructions

### ISSUE THREAD

**Issue by ldmberman** [cloudfoundry-incubator/diego-windows-release#4]
Hi,

I have set up a Windows Cell by trying both the CloudFormation script and the step-by-step process. Below are some things that I believe are missing in the instructions.

1) The security group of a NAT VM must allow traffic from the Windows subnet. Having a note about it or perhaps some additional CloudFormation templates setting it up would be very helpful.

2) The user account configuration part is missing in the manual guide. Specifically I am talking about these commands:
  
```
"net user containerizer ",
{
  "Ref": "ContainerizerPassword"
},
" /ADD",
"\n",
"net localgroup administrators containerizer /ADD",
"\n"
```

3) By default, Cloud Controller does not know about the Windows stack. In order to push Windows apps the stack needs [to be registered](http://apidocs.cloudfoundry.org/223/stacks/create_a_stack.html). I believe the diego-windows scripts could handle it for us, or at least mentioning it in INSTALL.md would be somewhat helpful.

I could come with a pull request if you wish.

**Comment by benmoss** [comment]
The manual install instructions do say that the user you install with needs to be an administrative user. The `containerizer` user you see there in the Cloudformation template it just the user we create on those installs. 

I added a note in the install docs about the NAT security group and enabling the Windows stack. There's not anything we can do for the latter, since it needs to be configured inside of the Cloud Controller, and so needs to be configured with the rest of your CF deploy.
